//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout_Checkin_Date
    {
        public int Checkout_Date_ID { get; set; }
        public Nullable<int> Tasks_Equipment_ID { get; set; }
        public Nullable<System.DateTime> Checkout_Date { get; set; }
        public Nullable<System.DateTime> Checkin_Date { get; set; }
        public Nullable<int> Checkout_ID { get; set; }
    
        public virtual Checkout_Checkin Checkout_Checkin { get; set; }
        public virtual Tasks_Equipment Tasks_Equipment { get; set; }
    }
}
