//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_On_Hand
    {
        public int Inventory_On_Hand_ID { get; set; }
        public int Inventory_ID { get; set; }
        public decimal Quantity { get; set; }
        public int WriteoffInventory_ID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual WriteOff_Inventory WriteOff_Inventory { get; set; }
    }
}
