//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_Line
    {
        public int Rental_Line_ID { get; set; }
        public int Inventory_ID { get; set; }
        public string Rental_Name { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
