//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int Rental_ID { get; set; }
        public int Rental_Status_ID { get; set; }
        public int Supplier_ID { get; set; }
        public string Rental_Name { get; set; }
        public decimal Rental_Cost { get; set; }
    
        public virtual Rental_Status Rental_Status { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
