//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_Request
    {
        public int Rental_Request_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public string Rental_Item { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<int> Rental_Request_Status_ID { get; set; }
    
        public virtual Rental_Request_Status Rental_Request_Status { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
