//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subcontractor_Phase
    {
        public int Subcontractor_Phase_ID { get; set; }
        public Nullable<int> Subcontractor_ID { get; set; }
        public Nullable<int> Phase_ID { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Subcontractor Subcontractor { get; set; }
    }
}
