//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Order
    {
        public int Supplier_Order_ID { get; set; }
        public int Project_ID { get; set; }
        public int Order_Status_ID { get; set; }
        public int Payment_Type_ID { get; set; }
        public int Employee_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Order_Items { get; set; }
        public decimal Total_Cost { get; set; }
        public int Supplier_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order_Status Order_Status { get; set; }
        public virtual Payment_Type Payment_Type { get; set; }
        public virtual Project Project { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier_Order Supplier_Order1 { get; set; }
        public virtual Supplier_Order Supplier_Order2 { get; set; }
    }
}
