//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier_Request()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int Supplier_Request_ID { get; set; }
        public string Item_Name { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Supplier_Request_Status_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual Supplier_Request_Status Supplier_Request_Status { get; set; }
    }
}
