//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks_Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks_Equipment()
        {
            this.Checkout_Checkin_Date = new HashSet<Checkout_Checkin_Date>();
        }
    
        public int Tasks_Equipment_ID { get; set; }
        public int Task_ID { get; set; }
        public int Equipment_ID { get; set; }
        public string Checkout_Equipment { get; set; }
        public string Checkin_Equipment { get; set; }
        public Nullable<decimal> Quantity_Checkout { get; set; }
        public Nullable<decimal> Quantity_Checkin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkout_Checkin_Date> Checkout_Checkin_Date { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Task Task { get; set; }
    }
}
