//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF370GabriQAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_ID { get; set; }
        public int User_Role_ID { get; set; }
        public int Employee_ID { get; set; }
        public int Password_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Password_History Password_History { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
